#! /bin/bash
NAME=fortunebot
BINPATH=/usr/local/bin/$NAME
PIDDIR=/var/run/$NAME
LOGDIR=/var/log/$NAME
CONFDIR=/var/lib/$NAME

# Check if the fortunebot python package is installed
python -Ec "import os; os.chdir('/'); import $NAME" &>/dev/null
if [ $? == 1 ]; then
    python setup.py install
fi

# Add user
id -u $NAME &>/dev/null
if [ $? != 0 ]; then
    adduser --quiet --system --group --no-create-home --disabled-login --shell /bin/false $NAME
fi

# Copy scripts
cp init/$NAME /etc/init.d/$NAME
chmod 755 /etc/init.d/$NAME
if [ "$1" == "boot" ]; then
    update-rc.d fortunebot defaults 99
else
    update-rc.d fortunebot stop 99 0 1 2 3 4 5 6 .
fi

# Set up environment
mkdir -p $PIDDIR $LOGDIR $CONFDIR
cp config/$NAME.conf.example $CONFDIR
cp $NAME/botrunner.py $BINPATH
chmod 755 $BINPATH
chown -R $NAME:$NAME $BINPATH $PIDDIR $LOGDIR $CONFDIR
