#! /bin/bash
NAME=fortunebot
HOMEDIR=/opt/$NAME
PIDDIR=/var/run/$NAME
LOGDIR=/var/log/$NAME

# Check if the fortunebot package is installed
python -Ec "import os; os.chdir('/'); import $NAME" &>/dev/null
if [ $? == 1 ]; then
    python setup.py install
fi

# Set up pidfile and logfile directories
id -u "$NAME" &>/dev/null
if [ $? != 0 ]; then
    adduser --quiet --system --group --home $HOMEDIR --disabled-login --shell /bin/false $NAME
fi
if [ ! -d $PIDDIR ]; then
    mkdir -p $PIDDIR
fi
if [ ! -d $LOGDIR ]; then
    mkdir -p $LOGDIR
fi
chown $NAME:$NAME $PIDDIR
chown $NAME:$NAME $LOGDIR

# Copy scripts
cp init/$NAME /etc/init.d/$NAME
chmod 755 /etc/init.d/$NAME
if [ "$1" == "boot" ]; then
    update-rc.d fortunebot defaults 99
else
    update-rc.d fortunebot stop 99 0 1 2 3 4 5 6 .
fi

# Set up home
mkdir -p $HOMEDIR/bin $HOMEDIR/config $HOMEDIR/data
cp $NAME/botrunner.py $HOMEDIR/bin/$NAME
cp config/$NAME.conf.example $HOMEDIR/config/
chmod 755 $HOMEDIR/bin/$NAME
chown -R $NAME:$NAME $HOMEDIR

