#! /bin/bash
NAME=fortunebot
PIDDIR=/var/run/$NAME
LOGDIR=/var/log/$NAME

# Remove pidfile and logfile directories
if [ -d $PIDDIR ]; then
    rm -r $PIDDIR
fi
if [ -d $LOGDIR ]; then
    rm -r $LOGDIR
fi

# Remove init script and binary
if [ -f /etc/init.d/$NAME ]; then
    rm /etc/init.d/$NAME
    update-rc.d fortunebot remove
fi
if [ -f /usr/local/bin/$NAME ]; then
    rm /usr/local/bin/$NAME
fi

# Remove daemon user
id -u "$NAME" &>/dev/null
if [ $? == 0 ]; then
    deluser --quiet --system --remove-home $NAME
    deluser --quiet --system --group $NAME
fi

# Uninstall the fortunebot package
python -Ec "import os; os.chdir('/'); import $NAME" &>/dev/null
if [ $? == 0 ]; then
    pip uninstall -y $NAME
fi

