#! /bin/bash

user=`whoami`
if [ "$user" != "root" ]; then
    echo "You must be root to run this command!" >&2
    exit 1
fi

NAME=fortunebot
CONFDIR=/var/lib/$NAME
PIDDIR=/var/run/$NAME
LOGDIR=/var/log/$NAME

# Remove pidfile and logfile directories
if [ -d $PIDDIR ]; then
    rm -r $PIDDIR
fi
if [ -d $LOGDIR ]; then
    rm -r $LOGDIR
fi
if [ -d $CONFDIR ]; then
    rm -r $CONFDIR
fi

# Remove init script
if [ -f /etc/init.d/$NAME ]; then
    rm /etc/init.d/$NAME
    update-rc.d fortunebot remove
fi

# Remove daemon user
id -u "$NAME" &>/dev/null
if [ $? == 0 ]; then
    deluser --quiet --system $NAME
    deluser --quiet --system --group $NAME
fi

# Uninstall the fortunebot package
python -Ec "import os; os.chdir('/'); import $NAME" &>/dev/null
if [ $? == 0 ]; then
    pip uninstall -y $NAME
fi

